// site/src/components/layout/Stack.tsx
import { type ComponentChildren } from "preact";
import "./Layout.css";

interface StackProps {
  children: ComponentChildren;
  gap?: string;
  align?: "start" | "center" | "end" | "stretch";
  className?: string;
}

export function Stack({
  children,
  gap = "1rem",
  align = "stretch",
  className = "",
}: StackProps) {
  return (
    <div
      class={`layout-stack ${className}`}
      style={{ gap, alignItems: align } as any}
    >
      {children}
    </div>
  );
}

// site/src/components/layout/Stack.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import './Layout.css';

  interface Props {
    children: Snippet;
    gap?: string;
    align?: "start" | "center" | "end" | "stretch";
    class?: string;
  }

  let { children, gap = "1rem", align = "stretch", class: className = "" }: Props = $props();
</script>

<div
  class="layout-stack {className}"
  style:gap
  style:align-items={align}
>
  {@render children()}
</div>
