// site/src/components/builder/SurfaceManager.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import type { ConfigState } from "../../lib/state/ConfigState.svelte";
  import SurfaceRow from "./SurfaceRow.svelte";

  const configState = getContext<ConfigState>("config");
  let config = $derived(configState.config);

  let newGroupName = $state("");
  let error = $state<string | null>(null);

  function handleError(fn: () => void): void {
    try {
      fn();
      error = null;
    } catch (e: unknown) {
      if (e instanceof Error) {
        error = e.message;
      } else {
        error = String(e);
      }
      setTimeout(() => (error = null), 3000);
    }
  }

  function handleAddGroup(): void {
    if (newGroupName.trim()) {
      handleError(() => {
        configState.addGroup(newGroupName.trim());
        newGroupName = "";
      });
    }
  }

  // --- Drag and Drop (Groups) ---
  let draggingGroupIndex: number | null = null;

  interface DragData {
    type: "group" | "surface";
    index?: number;
    groupIndex?: number;
    surfaceIndex?: number;
  }

  function handleGroupDragStart(e: DragEvent, index: number): void {
    draggingGroupIndex = index;
    if (e.dataTransfer) {
      e.dataTransfer.effectAllowed = "move";
      e.dataTransfer.setData(
        "application/json",
        JSON.stringify({ type: "group", index }),
      );
    }
  }

  function handleGroupDragOver(e: DragEvent, index: number): void {
    e.preventDefault(); // Allow drop
    if (draggingGroupIndex === null || draggingGroupIndex === index) return;
    if (e.dataTransfer) {
      e.dataTransfer.dropEffect = "move";
    }
  }

  function handleGroupDrop(e: DragEvent, index: number): void {
    e.preventDefault();

    // Check for surface drop first
    if (e.dataTransfer) {
      try {
        const data = e.dataTransfer.getData("application/json");
        if (data) {
          const parsed = JSON.parse(data) as DragData;
          if (
            parsed.type === "surface" &&
            typeof parsed.groupIndex === "number" &&
            typeof parsed.surfaceIndex === "number"
          ) {
            // Append to end of this group
            const targetSurfaceIndex = config.groups[index].surfaces.length;
            configState.moveSurface(
              parsed.groupIndex,
              parsed.surfaceIndex,
              index,
              targetSurfaceIndex,
            );
            return;
          }
        }
      } catch {
        // Ignore parse errors, might be group drag
      }
    }

    if (draggingGroupIndex === null) return;

    handleError(() => {
      configState.moveGroup(draggingGroupIndex, index);
    });
    draggingGroupIndex = null;
  }
</script>

<div>
  <h3 class="text-strong" style="margin-bottom: 1rem;">Surfaces</h3>

  {#if error}
    <div
      style="padding: 0.75rem; margin-bottom: 1rem; border-radius: 6px; background: var(--hue-error); color: white; font-size: 0.9rem;"
    >
      {error}
    </div>
  {/if}

  <div style="display: flex; flex-direction: column; gap: 2rem;">
    {#if config.groups.length === 0}
      <div
        class="surface-workspace bordered"
        style="padding: 2rem; border-radius: 8px; text-align: center;"
      >
        <p class="text-subtle" style="margin: 0;">No groups yet.</p>
        <p
          class="text-subtlest"
          style="font-size: 0.85rem; margin-top: 0.5rem;"
        >
          Create a group to start adding surfaces.
        </p>
      </div>
    {/if}

    {#each config.groups as group, groupIndex (group.name)}
      <div
        class="surface-card bordered"
        style="padding: 1rem; border-radius: 8px; cursor: grab;"
        draggable="true"
        ondragstart={(e) => {
          handleGroupDragStart(e, groupIndex);
        }}
        ondragover={(e) => {
          handleGroupDragOver(e, groupIndex);
        }}
        ondrop={(e) => {
          handleGroupDrop(e, groupIndex);
        }}
        role="listitem"
      >
        <div
          style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;"
        >
          <div
            style="display: flex; align-items: center; gap: 0.5rem; flex: 1;"
          >
            <span class="text-subtle" style="cursor: grab;">☰</span>
            <input
              type="text"
              value={group.name}
              oninput={(e) => {
                const val = e.currentTarget.value;
                handleError(() => {
                  configState.updateGroup(groupIndex, {
                    name: val,
                  });
                });
              }}
              class="text-strong"
              style="background: transparent; border: none; font-size: 1.1rem; font-weight: bold; width: 100%;"
            />
          </div>
          <button
            onclick={() => {
              configState.removeGroup(groupIndex);
            }}
            class="text-subtle"
            style="background: transparent; border: none; cursor: pointer; font-size: 1.2rem;"
            title="Remove Group"
          >
            &times;
          </button>
        </div>

        <div style="display: flex; flex-direction: column; gap: 0.5rem;">
          {#each group.surfaces as surface, surfaceIndex (surface.slug)}
            <SurfaceRow {surface} {groupIndex} {surfaceIndex} />
          {/each}

          <button
            onclick={() => {
              handleError(() => {
                configState.addSurface(groupIndex, {
                  slug: `new-surface-${Date.now()}`,
                  label: "New Surface",
                  polarity: "page",
                });
              });
            }}
            class="surface-workspace text-subtle bordered"
            style="padding: 0.5rem; border-radius: 6px; margin-top: 0.5rem; cursor: pointer; font-size: 0.9rem; width: 100%; text-align: center;"
          >
            + Add Surface
          </button>
        </div>
      </div>
    {/each}

    <div style="display: flex; gap: 0.5rem;">
      <input
        type="text"
        bind:value={newGroupName}
        placeholder="New Group Name"
        style="flex: 1; padding: 0.5rem; border-radius: 4px; border: 1px solid var(--border-subtle-token); background: transparent; color: var(--text-high-token);"
      />
      <button
        onclick={handleAddGroup}
        class="surface-action text-strong bordered"
        style="padding: 0.5rem 1rem; border-radius: 4px; cursor: pointer;"
      >
        Add Group
      </button>
    </div>
  </div>
</div>

// demo/src/components/ThemeBuilder/SurfaceManager.tsx
import type { SurfaceConfig } from "color-system/types";
import { useState } from "preact/hooks";
import { useConfig } from "../../context/ConfigContext";
import { useTheme } from "../../context/ThemeContext";
import { ContrastBadge } from "./ContrastBadge";

export function SurfaceManager() {
  const {
    config,
    addGroup,
    removeGroup,
    updateGroup,
    addSurface,
    removeSurface,
    updateSurface,
  } = useConfig();
  const [newGroupName, setNewGroupName] = useState("");
  const [error, setError] = useState<string | null>(null);

  const handleError = (fn: () => void) => {
    try {
      fn();
      setError(null);
    } catch (e: any) {
      setError(e.message);
      setTimeout(() => setError(null), 3000);
    }
  };

  const handleAddGroup = () => {
    if (newGroupName.trim()) {
      handleError(() => {
        addGroup(newGroupName.trim());
        setNewGroupName("");
      });
    }
  };

  return (
    <div>
      <h3 class="text-strong" style={{ marginBottom: "1rem" }}>
        Surfaces
      </h3>

      {error && (
        <div
          style={{
            padding: "0.75rem",
            marginBottom: "1rem",
            borderRadius: "6px",
            background: "var(--hue-error)",
            color: "white",
            fontSize: "0.9rem",
          }}
        >
          {error}
        </div>
      )}

      <div style={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
        {config.groups.length === 0 && (
          <div
            class="surface-workspace bordered"
            style={{
              padding: "2rem",
              borderRadius: "8px",
              textAlign: "center",
            }}
          >
            <p class="text-subtle" style={{ margin: 0 }}>
              No groups yet.
            </p>
            <p
              class="text-subtlest"
              style={{ fontSize: "0.85rem", marginTop: "0.5rem" }}
            >
              Create a group to start adding surfaces.
            </p>
          </div>
        )}

        {config.groups.map((group, groupIndex) => (
          <div
            key={groupIndex}
            class="surface-card bordered"
            style={{ padding: "1rem", borderRadius: "8px" }}
          >
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                marginBottom: "1rem",
              }}
            >
              <input
                type="text"
                value={group.name}
                onInput={(e) =>
                  handleError(() =>
                    updateGroup(groupIndex, { name: e.currentTarget.value })
                  )
                }
                class="text-strong"
                style={{
                  background: "transparent",
                  border: "none",
                  fontSize: "1.1rem",
                  fontWeight: "bold",
                  width: "100%",
                }}
              />
              <button
                onClick={() => removeGroup(groupIndex)}
                class="text-subtle"
                style={{
                  background: "transparent",
                  border: "none",
                  cursor: "pointer",
                  fontSize: "1.2rem",
                }}
                title="Remove Group"
              >
                &times;
              </button>
            </div>

            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "0.5rem",
              }}
            >
              {group.surfaces.map((surface, surfaceIndex) => (
                <SurfaceRow
                  key={surfaceIndex}
                  surface={surface}
                  onUpdate={(s) =>
                    handleError(() =>
                      updateSurface(groupIndex, surfaceIndex, s)
                    )
                  }
                  onRemove={() => removeSurface(groupIndex, surfaceIndex)}
                />
              ))}

              <button
                onClick={() =>
                  handleError(() =>
                    addSurface(groupIndex, {
                      slug: `new-surface-${Date.now()}`,
                      label: "New Surface",
                      polarity: "page",
                    })
                  )
                }
                class="surface-action text-strong bordered"
                style={{
                  padding: "0.5rem",
                  borderRadius: "4px",
                  marginTop: "0.5rem",
                  cursor: "pointer",
                  fontSize: "0.9rem",
                }}
              >
                + Add Surface
              </button>
            </div>
          </div>
        ))}

        <div style={{ display: "flex", gap: "0.5rem" }}>
          <input
            type="text"
            value={newGroupName}
            onInput={(e) => setNewGroupName(e.currentTarget.value)}
            placeholder="New Group Name"
            style={{
              flex: 1,
              padding: "0.5rem",
              borderRadius: "4px",
              border: "1px solid var(--border-subtle-token)",
              background: "transparent",
              color: "var(--text-high-token)",
            }}
          />
          <button
            onClick={handleAddGroup}
            class="surface-action text-strong bordered"
            style={{
              padding: "0.5rem 1rem",
              borderRadius: "4px",
              cursor: "pointer",
            }}
          >
            Add Group
          </button>
        </div>
      </div>
    </div>
  );
}

function SurfaceRow({
  surface,
  onUpdate,
  onRemove,
}: {
  surface: SurfaceConfig;
  onUpdate: (s: Partial<SurfaceConfig>) => void;
  onRemove: () => void;
}) {
  const [isExpanded, setIsExpanded] = useState(false);
  const { resolvedTheme } = useTheme();

  return (
    <div
      class="surface-workspace bordered"
      style={{ borderRadius: "6px", overflow: "hidden" }}
    >
      <div
        style={{
          padding: "0.75rem",
          display: "flex",
          alignItems: "center",
          gap: "0.5rem",
          cursor: "pointer",
        }}
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <span
          style={{
            transform: isExpanded ? "rotate(90deg)" : "rotate(0deg)",
            transition: "transform 0.2s",
          }}
        >
          ▶
        </span>
        <span class="text-strong" style={{ flex: 1 }}>
          {surface.label}
        </span>
        <ContrastBadge slug={surface.slug} mode={resolvedTheme} />
        <span class="text-subtle" style={{ fontSize: "0.8rem" }}>
          {surface.slug}
        </span>
      </div>

      {isExpanded && (
        <div
          style={{
            padding: "0.75rem",
            borderTop: "1px solid var(--border-subtle-token)",
            display: "flex",
            flexDirection: "column",
            gap: "0.75rem",
          }}
        >
          <label
            class="text-subtle"
            style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}
          >
            Label
            <input
              type="text"
              value={surface.label}
              onInput={(e) => onUpdate({ label: e.currentTarget.value })}
              style={{
                padding: "0.4rem",
                borderRadius: "4px",
                border: "1px solid var(--border-subtle-token)",
                background: "transparent",
                color: "var(--text-high-token)",
              }}
            />
          </label>
          <label
            class="text-subtle"
            style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}
          >
            Slug
            <input
              type="text"
              value={surface.slug}
              onInput={(e) => onUpdate({ slug: e.currentTarget.value })}
              style={{
                padding: "0.4rem",
                borderRadius: "4px",
                border: "1px solid var(--border-subtle-token)",
                background: "transparent",
                color: "var(--text-high-token)",
              }}
            />
          </label>
          <label
            class="text-subtle"
            style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}
          >
            Polarity
            <select
              value={surface.polarity}
              onChange={(e) =>
                onUpdate({ polarity: e.currentTarget.value as any })
              }
              style={{
                padding: "0.4rem",
                borderRadius: "4px",
                border: "1px solid var(--border-subtle-token)",
                background: "var(--surface-token)",
                color: "var(--text-high-token)",
              }}
            >
              <option value="page">Page</option>
              <option value="inverted">Inverted</option>
            </select>
          </label>

          <div
            style={{
              display: "flex",
              justifyContent: "flex-end",
              marginTop: "0.5rem",
            }}
          >
            <button
              onClick={(e) => {
                e.stopPropagation();
                onRemove();
              }}
              class="text-subtle"
              style={{
                color: "var(--hue-error)",
                background: "transparent",
                border: "none",
                cursor: "pointer",
                fontSize: "0.9rem",
              }}
            >
              Delete Surface
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
