// site/src/components/builder/ThemeBuilder.svelte
<script lang="ts">
  import {
    generateTheme,
    injectTheme,
  } from "@algebraic-systems/color-system/runtime";
  import { getContext } from "svelte";
  import type { ConfigState } from "../../lib/state/ConfigState.svelte";
  import type { ThemeState } from "../../lib/state/ThemeState.svelte";
  import "./ThemeBuilder.css";

  import AnchorsEditor from "./AnchorsEditor.svelte";
  import HueShiftEditor from "./HueShiftEditor.svelte";
  import KeyColorsEditor from "./KeyColorsEditor.svelte";
  import SurfaceManager from "./SurfaceManager.svelte";
  import VisualizerGraph from "./VisualizerGraph.svelte";

  import Cluster from "../layout/Cluster.svelte";

  const themeState = getContext<ThemeState>("theme");
  const configState = getContext<ConfigState>("config");

  let currentMode = $derived(themeState.mode);
  let config = $derived(configState.config);

  let activeTab = $state("preview");

  let styleElement: HTMLStyleElement | undefined = undefined;

  $effect(() => {
    try {
      // Clone config to avoid mutation in solve() triggering infinite loop
      const configClone = JSON.parse(JSON.stringify(config));
      const css = generateTheme(configClone, "#theme-builder-preview");
      // Pass undefined for target to append to head.
      styleElement = injectTheme(css, undefined, styleElement);
      if (styleElement) {
        styleElement.id = "theme-builder-styles";
      }
    } catch (e) {
      console.error("Solver failed:", e);
    }
  });

  $effect(() => {
    return () => {
      if (styleElement) {
        styleElement.remove();
      }
    };
  });
</script>

<div class="theme-builder-container">
  <aside class="theme-builder-sidebar surface-workspace">
    <div class="theme-builder-header">
      <h2 class="text-strong">Theme Builder</h2>
      <p class="text-subtle">Customize global system parameters.</p>
      <button
        onclick={() => configState.resetConfig()}
        class="surface-workspace bordered text-subtle"
        style="margin-top: 0.75rem; width: 100%; padding: 0.5rem; border-radius: 6px; cursor: pointer; font-size: 0.85rem; font-weight: 500;"
      >
        Reset to Default
      </button>
    </div>

    <AnchorsEditor />
    <KeyColorsEditor />
    <HueShiftEditor />
    <SurfaceManager />
  </aside>

  <main class="theme-builder-main" id="theme-builder-preview">
    <div class="surface-page theme-builder-preview-page">
      <div class="surface-card bordered theme-builder-preview-card">
        <!-- Header -->
        <div class="preview-section">
          <h1 class="text-strong" style="margin: 0 0 0.5rem 0">Preview Area</h1>
          <p class="text-subtle">
            This area is styled by the live config. Adjust the sliders on the
            left to see changes in real-time.
          </p>
          <div
            style="margin-top: 1rem; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem;"
          >
            <div>
              <p class="text-subtle" style="margin-bottom: 0.5rem;">
                Current Mode: <strong>{currentMode}</strong>
              </p>
              <button
                class="preview-button surface-action"
                onclick={() => themeState.toggle()}
              >
                Toggle Mode
              </button>
            </div>

            <div class="preview-tabs">
              <Cluster gap="0.5rem">
                <button
                  class="tab-button {activeTab === 'preview' ? 'active' : ''}"
                  onclick={() => (activeTab = "preview")}
                >
                  Preview
                </button>
                <button
                  class="tab-button {activeTab === 'graph' ? 'active' : ''}"
                  onclick={() => (activeTab = "graph")}
                >
                  Graph
                </button>
              </Cluster>
            </div>
          </div>
        </div>

        {#if activeTab === "preview"}
          <!-- Standard Controls -->
          <div class="preview-section">
            <h3 class="text-strong">Standard Surfaces</h3>
            <Cluster gap="1rem" align="center">
              <button
                class="surface-action text-strong bordered preview-button"
              >
                Action Button
              </button>
              <button
                class="surface-workspace text-subtle bordered preview-button"
              >
                Secondary
              </button>
              <div class="surface-workspace bordered preview-input">
                <span class="text-subtle">Input Field</span>
              </div>
            </Cluster>
          </div>

          <!-- Brand Controls -->
          <div class="preview-section">
            <h3 class="text-strong">Brand Integration</h3>
            <p class="text-subtle">
              Elements using the{" "}
              <code class="surface-workspace bordered preview-code">
                .hue-brand
              </code>{" "}
              utility.
            </p>

            <div class="hue-brand">
              <Cluster gap="1rem" align="center">
                <!-- Brand Button (Inverted) -->
                <button class="surface-spotlight text-strong preview-button">
                  Brand Button
                </button>

                <!-- Brand Card (Page Polarity + Tint) -->
                <div class="surface-card bordered preview-brand-card">
                  <span class="text-strong">Brand Tinted Card</span>
                </div>

                <!-- Brand Link -->
                <a href="#_top" class="text-link"> Brand Link </a>
              </Cluster>
            </div>
          </div>

          <!-- Typography Check -->
          <div class="preview-section">
            <div class="surface-workspace bordered preview-typography-card">
              <h3 class="text-strong">Typography & Contrast</h3>
              <p class="text-high-token">This is high-emphasis text.</p>
              <p class="text-subtle">
                This is subtle text for secondary information.
              </p>
              <p class="text-subtlest">This is subtlest text for metadata.</p>
            </div>
          </div>

          <!-- Dynamic Surface List -->
          <div class="preview-section">
            <h3 class="text-strong">All Surfaces</h3>
            {#if config.groups.length === 0 || config.groups.every((g) => g.surfaces.length === 0)}
              <div class="surface-workspace bordered preview-empty-state">
                <div class="preview-empty-icon">🎨</div>
                <div>
                  <h4 class="text-strong" style="margin: 0 0 0.5rem 0">
                    No Custom Surfaces
                  </h4>
                  <p class="text-subtle preview-empty-text">
                    Add groups and surfaces in the sidebar to see them appear
                    here. They will be generated as CSS classes like{" "}
                    <code>.surface-card</code>.
                  </p>
                </div>
              </div>
            {:else}
              <div style="display: flex; flex-direction: column; gap: 2rem;">
                {#each config.groups as group (group.name)}
                  {#if group.surfaces.length > 0}
                    <div>
                      <h4 class="text-subtle preview-group-title">
                        {group.name}
                      </h4>
                      <div class="preview-surface-grid">
                        {#each group.surfaces as surface (surface.slug)}
                          <div
                            class={`surface-${surface.slug} bordered preview-surface-card`}
                          >
                            <span class="text-strong preview-surface-label">
                              {surface.label}
                            </span>
                            <code class="text-subtle preview-surface-code">
                              .surface-{surface.slug}
                            </code>
                          </div>
                        {/each}
                      </div>
                    </div>
                  {/if}
                {/each}
              </div>
            {/if}
          </div>
        {:else}
          <VisualizerGraph />
        {/if}
      </div>
    </div>
  </main>
</div>

// demo/src/components/ThemeBuilder/ThemeBuilder.tsx
import { useState } from "preact/hooks";
import { useConfig } from "../../context/ConfigContext";
import { AnchorsEditor } from "./AnchorsEditor";
import { ExportPanel } from "./ExportPanel";
import { HueShiftEditor } from "./HueShiftEditor";
import { KeyColorsEditor } from "./KeyColorsEditor";
import { LiveThemeInjector } from "./LiveThemeInjector";
import { PresetSelector } from "./PresetSelector";
import { SurfaceManager } from "./SurfaceManager";

export function ThemeBuilder() {
  const { config } = useConfig();
  const [simulateHighContrast, setSimulateHighContrast] = useState(false);

  return (
    <div style={{ display: "flex", height: "100vh", paddingTop: "4rem" }}>
      <LiveThemeInjector simulateHighContrast={simulateHighContrast} />

      {/* Sidebar */}
      <aside
        style={{
          width: "350px",
          padding: "1.5rem",
          borderRight: "1px solid var(--border-subtle-token)",
          overflowY: "auto",
          display: "flex",
          flexDirection: "column",
          gap: "3rem",
        }}
        class="surface-workspace"
      >
        <div>
          <h2 class="text-strong" style={{ margin: "0 0 0.5rem 0" }}>
            Theme Builder
          </h2>
          <p class="text-subtle" style={{ margin: 0, fontSize: "0.9rem" }}>
            Customize global system parameters.
          </p>
          <label
            style={{
              display: "flex",
              alignItems: "center",
              gap: "0.5rem",
              marginTop: "1rem",
              cursor: "pointer",
            }}
          >
            <input
              type="checkbox"
              checked={simulateHighContrast}
              onChange={(e) => setSimulateHighContrast(e.currentTarget.checked)}
            />
            <span class="text-strong" style={{ fontSize: "0.9rem" }}>
              Simulate High Contrast
            </span>
          </label>
        </div>

        <PresetSelector />

        <KeyColorsEditor />
        <AnchorsEditor />
        <HueShiftEditor />
        <SurfaceManager />
        <ExportPanel />
      </aside>

      {/* Main Preview Area */}
      <main
        style={{ flex: 1, padding: "0", overflowY: "auto" }}
        id="theme-builder-preview"
      >
        <div
          class="surface-page"
          style={{ minHeight: "100%", padding: "2rem" }}
        >
          <div
            class="surface-card bordered"
            style={{
              padding: "2rem",
              borderRadius: "8px",
              maxWidth: "800px",
              margin: "0 auto",
              display: "flex",
              flexDirection: "column",
              gap: "2rem",
            }}
          >
            {/* Header */}
            <div>
              <h1 class="text-strong" style={{ margin: "0 0 0.5rem 0" }}>
                Preview Area
              </h1>
              <p class="text-subtle" style={{ margin: 0 }}>
                This area is styled by the live config. Adjust the sliders on
                the left to see changes in real-time.
              </p>
            </div>

            {/* Standard Controls */}
            <div>
              <h3 class="text-strong" style={{ marginBottom: "1rem" }}>
                Standard Surfaces
              </h3>
              <div
                style={{ display: "flex", gap: "1rem", alignItems: "center" }}
              >
                <button
                  class="surface-action text-strong bordered"
                  style={{
                    padding: "0.75rem 1.5rem",
                    borderRadius: "6px",
                    cursor: "pointer",
                    fontWeight: "bold",
                  }}
                >
                  Action Button
                </button>
                <button
                  class="surface-workspace text-subtle bordered"
                  style={{
                    padding: "0.75rem 1.5rem",
                    borderRadius: "6px",
                    cursor: "pointer",
                    fontWeight: "bold",
                  }}
                >
                  Secondary
                </button>
                <div
                  class="surface-workspace bordered"
                  style={{ padding: "0.5rem 1rem", borderRadius: "6px" }}
                >
                  <span class="text-subtle">Input Field</span>
                </div>
              </div>
            </div>

            {/* Brand Controls */}
            <div>
              <h3 class="text-strong" style={{ marginBottom: "1rem" }}>
                Brand Integration
              </h3>
              <p class="text-subtle" style={{ marginBottom: "1rem" }}>
                Elements using the{" "}
                <code
                  class="surface-workspace bordered"
                  style={{ padding: "0.2rem 0.4rem", borderRadius: "4px" }}
                >
                  .hue-brand
                </code>{" "}
                utility.
              </p>

              <div
                class="hue-brand"
                style={{
                  display: "flex",
                  gap: "1rem",
                  alignItems: "center",
                  flexWrap: "wrap",
                }}
              >
                {/* Brand Button (Inverted) */}
                <button
                  class="surface-spotlight text-strong"
                  style={{
                    padding: "0.75rem 1.5rem",
                    borderRadius: "6px",
                    cursor: "pointer",
                    fontWeight: "bold",
                    border: "none",
                  }}
                >
                  Brand Button
                </button>

                {/* Brand Card (Page Polarity + Tint) */}
                <div
                  class="surface-card bordered"
                  style={{ padding: "1rem", borderRadius: "8px" }}
                >
                  <span class="text-strong">Brand Tinted Card</span>
                </div>

                {/* Brand Link */}
                <a href="#" class="text-link">
                  Brand Link
                </a>
              </div>
            </div>

            {/* Typography Check */}
            <div
              class="surface-workspace bordered"
              style={{ padding: "1.5rem", borderRadius: "8px" }}
            >
              <h3 class="text-strong" style={{ marginTop: 0 }}>
                Typography & Contrast
              </h3>
              <p class="text-high-token">This is high-emphasis text.</p>
              <p class="text-subtle">
                This is subtle text for secondary information.
              </p>
              <p class="text-subtlest">This is subtlest text for metadata.</p>
            </div>

            {/* Dynamic Surface List */}
            <div>
              <h3 class="text-strong" style={{ marginBottom: "1rem" }}>
                All Surfaces
              </h3>

              {config.groups.length === 0 ||
              config.groups.every((g) => g.surfaces.length === 0) ? (
                <div
                  class="surface-workspace bordered"
                  style={{
                    padding: "3rem",
                    borderRadius: "8px",
                    textAlign: "center",
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    gap: "1rem",
                  }}
                >
                  <div style={{ fontSize: "2rem", opacity: 0.5 }}>🎨</div>
                  <div>
                    <h4 class="text-strong" style={{ margin: "0 0 0.5rem 0" }}>
                      No Custom Surfaces
                    </h4>
                    <p
                      class="text-subtle"
                      style={{ margin: 0, maxWidth: "400px" }}
                    >
                      Add groups and surfaces in the sidebar to see them appear
                      here. They will be generated as CSS classes like{" "}
                      <code>.surface-card</code>.
                    </p>
                  </div>
                </div>
              ) : (
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: "2rem",
                  }}
                >
                  {config.groups.map(
                    (group) =>
                      group.surfaces.length > 0 && (
                        <div key={group.name}>
                          <h4
                            class="text-subtle"
                            style={{
                              margin: "0 0 0.5rem 0",
                              fontSize: "0.9rem",
                              textTransform: "uppercase",
                              letterSpacing: "0.05em",
                            }}
                          >
                            {group.name}
                          </h4>
                          <div
                            style={{
                              display: "grid",
                              gridTemplateColumns:
                                "repeat(auto-fill, minmax(200px, 1fr))",
                              gap: "1rem",
                            }}
                          >
                            {group.surfaces.map((surface) => (
                              <div
                                key={surface.slug}
                                class={`surface-${surface.slug} bordered`}
                                style={{
                                  padding: "1.5rem",
                                  borderRadius: "8px",
                                  display: "flex",
                                  flexDirection: "column",
                                  gap: "0.5rem",
                                }}
                              >
                                <span
                                  class="text-strong"
                                  style={{ fontWeight: "bold" }}
                                >
                                  {surface.label}
                                </span>
                                <code
                                  class="text-subtle"
                                  style={{ fontSize: "0.8rem" }}
                                >
                                  .surface-{surface.slug}
                                </code>
                              </div>
                            ))}
                          </div>
                        </div>
                      )
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
